# Site settings
title: Microsoft TEs United
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Microsoft Technical Evangelists Blogs United so you can learn from the folks at your hackathon!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: timmyreilly
github_username:  timmyreilly

# Build settings
markdown: kramdown
